export interface SiteImageItem {
  id: string;
  labelEn: string;
  labelAr: string;
  section: string;
  currentUrl: string;
  description: string;
  descriptionAr?: string;
  year?: string;
  location?: string;
  locationAr?: string;
  aspectRatio: string;
}

export const DEFAULT_SITE_IMAGES: SiteImageItem[] = [
  {
    id: 'home-hero-villa',
    labelEn: 'Homepage Hero Villa (Twilight)',
    labelAr: 'صورة الهيدر الرئيسية (الفيلا والإنفينيتي بول)',
    section: 'Hero Banners',
    currentUrl: '/images/hero-villa.png',
    year: '2024',
    location: 'New Cairo, Egypt',
    locationAr: 'القاهرة الجديدة، مصر',
    description: 'Monumental travertine and glass villa at twilight with illuminated infinity pool.',
    descriptionAr: 'كتل معمارية متوازنة من الترافيرتين والزجاج عند الغسق مع مسبح عاكس.',
    aspectRatio: '16/9',
  },
  {
    id: 'hero-villa-2',
    labelEn: 'Cinematic Villa Angle II',
    labelAr: 'اللقطة السينمائية الثانية للفيلا',
    section: 'Hero Banners',
    currentUrl: '/images/hero-villa-2.jpg',
    year: '2024',
    location: 'Sheikh Zayed, Egypt',
    locationAr: 'الشيخ زايد، مصر',
    description: 'Cantilevered rooflines and lush courtyard vegetation at twilight.',
    descriptionAr: 'بروزات خرسانية كابولية ومساحات خضراء في فناء الفيلا عند الغروب.',
    aspectRatio: '16/9',
  },
  {
    id: 'hero-villa-3',
    labelEn: 'Minimalist Architecture Villa III',
    labelAr: 'الفيلا المعمارية التبسيطية',
    section: 'Hero Banners',
    currentUrl: '/images/hero-villa-3.jpg',
    year: '2024',
    location: 'Katameya Dunes, Egypt',
    locationAr: 'قطامية ديونز، مصر',
    description: 'Clean geometric lines, water reflections, and warm architectural lighting.',
    descriptionAr: 'خطوط هندسية نقية وانعكاسات مائية مع إضاءة معمارية دافئة.',
    aspectRatio: '16/9',
  },
  {
    id: 'projects-hero',
    labelEn: 'Projects Page Hero (Olive Tree Villa)',
    labelAr: 'هيدر صفحة المشاريع (الفيلا وشجرة الزيتون)',
    section: 'Hero Banners',
    currentUrl: '/images/projects-hero-villa.jpg',
    year: '2024',
    location: 'New Cairo, Egypt',
    locationAr: 'القاهرة الجديدة، مصر',
    description: 'Ultra-luxury modern villa at twilight with illuminated olive tree and reflecting pool.',
    descriptionAr: 'فيلا عصرية فائقة الفخامة مع شجرة زيتون مضاءة وفناء مائي عاكس.',
    aspectRatio: '16/9',
  },
  {
    id: 'services-hero',
    labelEn: 'Services Page Hero Colonnade',
    labelAr: 'هيدر صفحة الخدمات (الأعمدة المعمارية)',
    section: 'Hero Banners',
    currentUrl: '/images/services-hero-colonnade.jpg',
    year: '2024',
    location: 'Riyadh, KSA',
    locationAr: 'الرياض، السعودية',
    description: 'Rhythmic architectural colonnade and natural daylight filtering through canopy.',
    descriptionAr: 'إيقاع معماري متناسق للأعمدة وتسلل الضوء الطبيعي عبر الممرات.',
    aspectRatio: '16/9',
  },
  {
    id: 'studio-hero',
    labelEn: 'Studio Page Hero (HQ & Atelier)',
    labelAr: 'هيدر صفحة الاستوديو (المقر الرئيسي والمعمل)',
    section: 'Hero Banners',
    currentUrl: '/images/studio-firm-hero.jpg',
    year: '2024',
    location: 'Cairo & Riyadh',
    locationAr: 'القاهرة والرياض',
    description: 'Architectural studio headquarters with warm ambient lighting and material showcase.',
    descriptionAr: 'المقر الرئيسي لاستوديو إيوان مع إضاءة دافئة ومعرض للمواد المعمارية.',
    aspectRatio: '16/9',
  },
  {
    id: 'how-we-work-hero',
    labelEn: 'How We Work Process Hero',
    labelAr: 'هيدر منهجية العمل والتنفيذ',
    section: 'Hero Banners',
    currentUrl: '/images/how-we-work-hero.jpg',
    year: '2024',
    location: 'Cairo Studio HQ',
    locationAr: 'المقر الرئيسي، القاهرة',
    description: 'Architects analyzing blueprint details and tactile material samples.',
    descriptionAr: 'المهندسون يراجعون التفاصيل التنفيذية وعينات المواد الطبيعية.',
    aspectRatio: '16/9',
  },
  {
    id: 'careers-hero',
    labelEn: 'Careers Studio Master Hero',
    labelAr: 'هيدر صفحة الوظائف وفريق العمل',
    section: 'Hero Banners',
    currentUrl: '/images/careers-hero-viwan.jpg',
    year: '2024',
    location: 'VIWAN Atelier',
    locationAr: 'استوديو إيوان',
    description: 'High-end architectural design lab and creative workstations.',
    descriptionAr: 'مختبر التصميم المعماري ومساحات الابتكار والتطوير في إيوان.',
    aspectRatio: '16/9',
  },
  {
    id: 'consultation-banner',
    labelEn: 'Consultation & Meeting Banner',
    labelAr: 'صورة حجز الاستشارة الهندسية',
    section: 'Hero Banners',
    currentUrl: '/images/consultation-architects.jpg',
    year: '2024',
    location: 'VIWAN Meeting Suite',
    locationAr: 'قاعة الاجتماعات الرئيسية',
    description: 'Partner architects reviewing client requirements and schematic designs.',
    descriptionAr: 'جلسة استشارية هندسية لمراجعة متطلبات المشروع والمخططات الأولية.',
    aspectRatio: '16/9',
  },
  {
    id: 'service-architecture',
    labelEn: '01. Architecture Discipline',
    labelAr: '01. الهندسة المعمارية',
    section: 'The 8 Disciplines',
    currentUrl: '/images/service-architecture.jpg',
    year: '2024',
    location: 'Regional Portfolio',
    locationAr: 'مشاريع المنطقة',
    description: 'Contemporary residential and commercial architectural composition.',
    descriptionAr: 'صياغة معمارية متفردة للمشاريع السكنية والتجارية الكبرى.',
    aspectRatio: '16/10',
  },
  {
    id: 'service-interior',
    labelEn: '02. Interior Design Discipline',
    labelAr: '02. التصميم الداخلي الفاخر',
    section: 'The 8 Disciplines',
    currentUrl: '/images/service-interior-design.jpg',
    year: '2024',
    location: 'Cairo & Riyadh',
    locationAr: 'القاهرة والرياض',
    description: 'Ultra-luxury interior living space with bespoke millwork and cove lighting.',
    descriptionAr: 'فضاءات داخلية استثنائية بتشطيبات رخامية وأعمال خشبية مصممة خصيصاً.',
    aspectRatio: '16/10',
  },
  {
    id: 'service-urban',
    labelEn: '03. Urban Planning Discipline',
    labelAr: '03. التخطيط والتصميم العمراني',
    section: 'The 8 Disciplines',
    currentUrl: '/images/service-urban-design.jpg',
    year: '2024',
    location: 'New Capital, Egypt',
    locationAr: 'العاصمة الإدارية، مصر',
    description: 'Sustainable masterplanning and pedestrian-friendly urban frameworks.',
    descriptionAr: 'مخططات عمرانية متكاملة تعزز المشهد البيئي والاستدامة الحضرية.',
    aspectRatio: '16/10',
  },
  {
    id: 'service-landscape',
    labelEn: '04. Landscape Architecture',
    labelAr: '04. هندسة وتنسيق المواقع',
    section: 'The 8 Disciplines',
    currentUrl: '/images/service-landscape-design.jpg',
    year: '2024',
    location: 'Sheikh Zayed, Egypt',
    locationAr: 'الشيخ زايد، مصر',
    description: 'Private villa garden with indigenous Mediterranean flora and water features.',
    descriptionAr: 'حدائق سكنية تجمع بين النباتات الملائمة بيئياً والعناصر المائية.',
    aspectRatio: '16/10',
  },
  {
    id: 'service-supervision',
    labelEn: '05. Construction Supervision',
    labelAr: '05. الإشراف الهندسي والتنفيذي',
    section: 'The 8 Disciplines',
    currentUrl: '/images/service-construction-supervision.jpg',
    year: '2024',
    location: 'On-Site Execution',
    locationAr: 'المواقع الإنشائية',
    description: 'Rigorous engineering site supervision, quality audits, and structural oversight.',
    descriptionAr: 'إشراف ميداني هندسي صارم وضبط جودة المواد وفق أعلى المعايير.',
    aspectRatio: '16/10',
  },
  {
    id: 'service-engineering',
    labelEn: '06. Sustainable Engineering & MEP',
    labelAr: '06. الهندسة المستدامة وكفاءة الطاقة',
    section: 'The 8 Disciplines',
    currentUrl: '/images/service-engineering.jpg',
    year: '2024',
    location: 'Riyadh, KSA',
    locationAr: 'الرياض، السعودية',
    description: 'Bioclimatic design, solar orientation, and energy-efficient building systems.',
    descriptionAr: 'أنظمة كهروميكانيكية متطورة وحلول طاقة مستدامة متوافقة مع المناخ.',
    aspectRatio: '16/10',
  },
  {
    id: 'service-fitout',
    labelEn: '07. Turnkey Contracting & Fitout',
    labelAr: '07. المقاولات المتكاملة والمفتاح باليد',
    section: 'The 8 Disciplines',
    currentUrl: '/images/service-fitout-marble.jpg',
    year: '2024',
    location: 'Cairo, Egypt',
    locationAr: 'القاهرة، مصر',
    description: 'Precision Italian Calacatta marble wall cladding and turnkey execution.',
    descriptionAr: 'تنفيذ دقيق لتكسيات الرخام الإيطالي وأعمال التشطيب الشاملة.',
    aspectRatio: '16/10',
  },
  {
    id: 'service-management',
    labelEn: '08. Historic Restoration & PM',
    labelAr: '08. الترميم وإحياء التراث وإدارة المشاريع',
    section: 'The 8 Disciplines',
    currentUrl: '/images/service-project-management.jpg',
    year: '2024',
    location: 'Old Damascus & Historic Cairo',
    locationAr: 'دمشق القديمة والقاهرة التاريخية',
    description: 'Restoring historic masonry, mashrabiya details, and heritage preservation.',
    descriptionAr: 'صيانة وترميم الواجهات التراثية والمشربيات والمباني التاريخية الأصيلة.',
    aspectRatio: '16/10',
  },
  {
    id: 'project-private-residence',
    labelEn: 'Private Residence Cairo',
    labelAr: 'إقامة خاصة فاخرة بالقاهرة',
    section: 'Featured Projects',
    currentUrl: '/images/project-private-residence.png',
    year: '2024',
    location: 'New Cairo, Egypt',
    locationAr: 'القاهرة الجديدة، مصر',
    description: 'Luxury residential masterwork blending natural stone, glass, and private courtyard.',
    descriptionAr: 'تحفة سكنية معاصرة تجمع بين الحجر الطبيعي والزجاج والفناء الداخلي الخاص.',
    aspectRatio: '16/10',
  },
  {
    id: 'project-commercial-tower',
    labelEn: 'King Fahd Commercial Tower',
    labelAr: 'برج طريق الملك فهد التجاري',
    section: 'Featured Projects',
    currentUrl: '/images/project-commercial-tower.png',
    year: '2024',
    location: 'King Fahd Rd, Riyadh, KSA',
    locationAr: 'طريق الملك فهد، الرياض، السعودية',
    description: 'Iconic commercial headquarters with bioclimatic facade louvers and glass curtain.',
    descriptionAr: 'صرح تجاري مع كواسر شمسية ذكية وواجهات زجاجية مزدوجة متطورة.',
    aspectRatio: '16/10',
  },
  {
    id: 'project-lake-house',
    labelEn: 'Lake House Waterfront Villa',
    labelAr: 'فيلا الواجهة المائية والبحيرة',
    section: 'Featured Projects',
    currentUrl: '/images/project-lake-house.png',
    year: '2023',
    location: 'Red Sea Coast, Egypt',
    locationAr: 'ساحل البحر الأحمر، مصر',
    description: 'Waterfront residence opening completely to marine breeze and infinity horizons.',
    descriptionAr: 'إقامة شاطئية بتصميم مفتوح بالكامل على الأفق البحري والنسيم الطبيعي.',
    aspectRatio: '16/10',
  },
  {
    id: 'project-hillside-villa',
    labelEn: 'Hillside Contemporary Villa',
    labelAr: 'فيلا المرتفعات التضاريسية',
    section: 'Featured Projects',
    currentUrl: '/images/project-hillside-villa.png',
    year: '2024',
    location: 'Katameya Heights, Egypt',
    locationAr: 'قطامية هايتس، مصر',
    description: 'Terraced residential architecture following natural topographic contours.',
    descriptionAr: 'تكوين معماري مدرج يتناغم بسلاسة مع التضاريس الطبيعية للموقع.',
    aspectRatio: '16/10',
  },
  {
    id: 'project-executive-office',
    labelEn: 'Executive Corporate Suite',
    labelAr: 'مقر إداري ومكتب تنفيذي',
    section: 'Featured Projects',
    currentUrl: '/images/project-executive-office.png',
    year: '2024',
    location: 'Financial District, New Cairo',
    locationAr: 'حي المال والأعمال، القاهرة الجديدة',
    description: 'Minimalist corporate headquarters with acoustic timber paneling and glass partitions.',
    descriptionAr: 'مكتب تنفيذي راقٍ يجمع بين الخشب العازل للصوت والقواطع الزجاجية.',
    aspectRatio: '16/10',
  },
  {
    id: 'project-majlis',
    labelEn: 'Modern Heritage Majlis',
    labelAr: 'المجلس النجدي المعاصر',
    section: 'Featured Projects',
    currentUrl: '/images/project-majlis.png',
    year: '2024',
    location: 'Diriyah, Riyadh, KSA',
    locationAr: 'الدرعية، الرياض، السعودية',
    description: 'Contemporary interpretation of traditional Najdi hospitality spaces with bespoke lighting.',
    descriptionAr: 'إعادة صياغة عصرية للمجلس التراثي بأصالة نجدية وإضاءة خافتة فاخرة.',
    aspectRatio: '16/10',
  },
  {
    id: 'material-stone',
    labelEn: 'Natural Travertine & Limestone',
    labelAr: 'حجر الترافيرتين والحجر الجيري الطبيعي',
    section: 'Architectural Materials',
    currentUrl: '/images/material-stone.png',
    year: '2024',
    location: 'Material Lab',
    locationAr: 'مختبر المواد',
    description: 'Textured tactile stone specimens selected for enduring durability and desert warmth.',
    descriptionAr: 'عينات حجرية طبيعية عالية الجودة تجمع بين الديمومة ودفء الصحراء.',
    aspectRatio: '1/1',
  },
  {
    id: 'material-wood',
    labelEn: 'Smoked Oak & Bespoke Millwork',
    labelAr: 'خشب البلوط المعتق والأعمال الخشبية',
    section: 'Architectural Materials',
    currentUrl: '/images/material-wood.png',
    year: '2024',
    location: 'Material Lab',
    locationAr: 'مختبر المواد',
    description: 'Grain-matched sustainable timber and fluted paneling details.',
    descriptionAr: 'أخشاب مستدامة بتفاصيل معمارية دقيقة وتشطيبات غير لامعة.',
    aspectRatio: '1/1',
  },
  {
    id: 'material-metal',
    labelEn: 'Aged Bronze & Crafted Metals',
    labelAr: 'البرونز المعتق والمعادن المشغولة',
    section: 'Architectural Materials',
    currentUrl: '/images/material-metal.png',
    year: '2024',
    location: 'Material Lab',
    locationAr: 'مختبر المواد',
    description: 'Custom architectural metal profiles, trims, and patinated bronze fixtures.',
    descriptionAr: 'معادن معمارية مشغولة يدوياً وتفاصيل برونزية بتعتيق فاخر.',
    aspectRatio: '1/1',
  },
  {
    id: 'material-fabric',
    labelEn: 'Bespoke Linens & Bouclé',
    labelAr: 'الأقمشة الفاخرة والكتان الطبيعي',
    section: 'Architectural Materials',
    currentUrl: '/images/material-fabric.png',
    year: '2024',
    location: 'Material Lab',
    locationAr: 'مختبر المواد',
    description: 'Tactile natural upholstery, acoustic wall fabrics, and curated textures.',
    descriptionAr: 'منسوجات راقية وأقمشة جدارية عازلة للصوت بتطريزات فخمة.',
    aspectRatio: '1/1',
  },
  {
    id: 'careers-gallery-1',
    labelEn: 'Architectural Design Studio Lab',
    labelAr: 'مختبر التصميم والتطوير المعماري',
    section: 'Studio & Careers',
    currentUrl: '/images/careers-gallery-1.jpg',
    year: '2024',
    location: 'VIWAN Atelier',
    locationAr: 'استوديو إيوان',
    description: 'Collaborative architectural workspace with multi-monitor CAD/BIM stations.',
    descriptionAr: 'بيئة عمل تفاعلية مجهزة بمحطات عمل متقدمة للتصميم والنمذجة المعمارية.',
    aspectRatio: '4/3',
  },
  {
    id: 'careers-gallery-2',
    labelEn: 'Physical Material Selection Lab',
    labelAr: 'مختبر عينات المواد الطبيعية',
    section: 'Studio & Careers',
    currentUrl: '/images/careers-gallery-2.jpg',
    year: '2024',
    location: 'Material Library',
    locationAr: 'مكتبة الخامات',
    description: 'Selecting natural stone slabs, veneer finishes, and bronze hardware.',
    descriptionAr: 'انتقاء عينات الرخام والأخشاب والقطع المعدنية لكل مشروع بعناية.',
    aspectRatio: '4/3',
  },
  {
    id: 'careers-gallery-3',
    labelEn: 'Design Critique & 3D Review',
    labelAr: 'جلسة النقد المعماري والمراجعة البصرية',
    section: 'Studio & Careers',
    currentUrl: '/images/careers-gallery-3.jpg',
    year: '2024',
    location: 'Design Review Suite',
    locationAr: 'قاعة المراجعة والتطوير',
    description: 'Senior partners and project directors reviewing spatial layouts.',
    descriptionAr: 'مراجعة المخططات الفراغية مع الشركاء المؤسسين ومديري المشاريع.',
    aspectRatio: '4/3',
  },
  {
    id: 'careers-gallery-4',
    labelEn: 'Site Execution & Quality Check',
    labelAr: 'المتابعة الميدانية والتدقيق التنفيذي',
    section: 'Studio & Careers',
    currentUrl: '/images/careers-gallery-4.jpg',
    year: '2024',
    location: 'Active Construction Site',
    locationAr: 'الموقع الإنشائي',
    description: 'Architects inspecting structural alignment and facade substructure.',
    descriptionAr: 'المهندسون يدققون تفاصيل الواجهات والهيكل الإنشائي بالموقع.',
    aspectRatio: '4/3',
  },
  {
    id: 'regional-map',
    labelEn: 'Regional Reach Map Asset',
    labelAr: 'خريطة التواجد الإقليمي للشرق الأوسط',
    section: 'Studio & Careers',
    currentUrl: '/images/regional-map.png',
    year: '2024',
    location: 'Middle East Region',
    locationAr: 'منطقة الشرق الأوسط',
    description: 'Cartographic representation of active projects across Cairo, Riyadh, and Damascus.',
    descriptionAr: 'تمثيل جغرافي لمشاريع واستوديوهات إيوان في القاهرة والرياض ودمشق.',
    aspectRatio: '16/9',
  },
  {
    id: 'impact-airplane-banner',
    labelEn: 'Airplane Towing VIWAN Brand Banner Over Coastal Sea',
    labelAr: 'طائرة تحلق بشعار إيوان فوق مياه البحر',
    section: 'Hero Banners',
    currentUrl: '/images/airplane-banner-viwan.jpg',
    year: '2026',
    location: 'Mediterranean Coast',
    locationAr: 'الساحل المتوسطي',
    description: 'A sleek white aircraft towing an aerial banner with the VIWAN logo over clear blue sea.',
    descriptionAr: 'طائرة بيضاء أنيقة تحلق في سماء صافية فوق مياه البحر وتسحب شعار استوديو إيوان.',
    aspectRatio: '16/9',
  },
];
